#
# Licensed under the GPL License. You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#
# THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
# PURPOSE.
#

version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.sun.activation:jakarta.activation
    versions:
    - ">= 2.0.0"
  - dependency-name: com.sun.mail:jakarta.mail
    versions:
    - ">= 2.0.0"
  - dependency-name: jakarta.activation:jakarta.activation-api
    versions:
    - ">= 2.0.0"
  - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
    versions:
    - ">= 3.0.0"
  - dependency-name: jakarta.el:jakarta.el-api
    versions:
    - ">= 4.0.0"
  - dependency-name: jakarta.inject:jakarta.inject-api
    versions:
    - ">= 2.0.0"
  - dependency-name: jakarta.servlet:jakarta.servlet-api
    versions:
    - ">= 5.0.0"
  - dependency-name: jakarta.servlet.jsp:jakarta.servlet.jsp-api
    versions:
    - ">= 3.0.0"
  - dependency-name: jakarta.transaction:jakarta.transaction-api
    versions:
    - ">= 2.0.0"
  - dependency-name: org.apache.tomcat:tomcat-catalina
    versions:
    - ">= 10.0.0"
  - dependency-name: org.apache.tomcat:tomcat-coyote
    versions:
    - ">= 10.0.0"
  - dependency-name: org.apache.tomcat:tomcat-dbcp
    versions:
    - ">= 10.0.0"
  - dependency-name: org.apache.tomcat:tomcat-jasper
    versions:
    - ">= 10.0.0"
  - dependency-name: org.eclipse.jetty:jetty-jspc-maven-plugin
    versions:
    - ">= 11.0.0"
  - dependency-name: org.glassfish.web:jakarta.servlet.jsp.jstl
    versions:
    - ">= 2.0.0"
