language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
  - secure: v7aD00cje5ZqZ/Oq8mtZzjfsGNVNI23RAw9aUl0KHymIWi6/ARhfMf5gOR40g8CGPQEXgv6CTQfJlTKohvObZFD1unjoI2htrN5qK3kct2PaY1i/tgQRk6HTvei+VIXXb72HTDUTyPlevt1gk1bCUBZlxlj3rSwI140/ryd/ySU=
  - secure: R1P1NYZiVyNp1ZOK+zugM2ZJFG17FMIV3g7kZarwP14MbqMm9ix4r3YC1UX5/vEXQoOMM7xwOeCYWIXgUQZMOOqU12DqTOk8QXoG881mGqUooAFVq/KEwEmQvH107/9a5/q5n+Wp7/xF/BZ8k5uKRzyrnr5p6mmQ4AFnHes12sw=

addons:
  coverity_scan:
    project:
      name: hazendaz/psi-probe
      description: Build submitted via Travis CI
    notification_email: jeremylandis@hotmail.com
    build_command_prepend: ./mvnw clean
    build_command: ./mvnw install -DskipTests -B -V
    branch_pattern: coverity_scan

install: true

script:
  - chmod -R 777 ./travis/script.sh
  - ./travis/script.sh

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh
