language: java

jdk:
  - oraclejdk11
  - oraclejdk8

env:
  global:
    - secure: f3myE88BdWOf/ZpKktmKyvGBz0ZNmtvxigGEOuFrZq73GSZlo4WnnCbKshqrt+1V/wwxxsKYmzd/WfzYSOWb/PXZ4sLCxNNSi65IVsBEGjWaXOT4JR/bZZpHN2kcEyp6DbEFEmnqJnNS6VF0siU98qN206h2D6qdMIz28+ZD/ZA=
    - secure: dZ3sQMR3y33myNZzNqLjkOVDs2jX5TFKyE59l+ltlVhewiuAgIh4EIoNyjbbf5SOZUOXgI1PfDjHHHWALXRKTE94NalK/zmxqo1T4OklHekzcNrN/b5NE8ykJ3xUoFy8+PosEHLkyNBRfci72+DZfRBUKqXSGcKPV+VF8bRimsU=
    - secure: V6WDO0vJB/LDgpZ/2/kEbPndExyfnUcVXoQBiPcTA5tsn4Q5eTGccio91XFfm9yNGLcGKEDOElZjmAqnungoSfEgOSRhy+t/4uq/BRDglTl9QlWktUwbbVGk2w6PoPmRke8V5CCsp/MDgbhDLstDNhTOHKhiKP9w3JHxnswfNFg=

addons:
  coverity_scan:
    project:
      name: hazendaz/psi-probe
      description: Build submitted via Travis CI
    notification_email: jeremylandis@hotmail.com
    build_command_prepend: "./mvnw clean --settings ./travis/settings.xml"
    build_command: "./mvnw install -B -V --settings ./travis/settings.xml"
    branch_pattern: coverity_scan

script:
  - chmod -R 777 ./travis/script.sh
  - "./travis/script.sh"

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"
